### ISSUE TITLE
Simple python model of pay-it-backwards

### ISSUE THREAD

**Issue by breakpointer** [ConsenSys/web3studio-bootleg#11]
## Overview

As an engineer so I know what parameters are important to the ERC definition create a simple model of the pay-it-backward concept that can be easily adjusted

### Reference

- [How ERC721 does it](https://ethfiddle.com/09YbyJRfiI)

### Questions

Does pay-it-backwards create equitable scenarios for the parties involved?
Is there a model or payment strategy that works better than others?

### Assumptions

That I can use a jupyter notebook to do something equivalent to 'back of the envelope' modeling for this
That I can time box it to a few hours of work to get some result

### Acceptance

A jupyter notebook we can share internally/externally to iterate on the modeling.

## Tasks

- [x] Setup notebook and commit it to the bootleg repo
- [x] Do a first-pass, very simple approach to the model. Fixed price, simple scheme for shared royalties (like equal % for all.. aka weight of 1, vs fractional weights). turns (sales) projected out to 100. 
- [x] Hand notebook off to someone who knows more about modeling to audition different models and figure out (through more advanced simulation) what works.

**Comment by breakpointer** [comment]
Some overlap with above but here are some notes on implementation:

First pass at modeling, set up simple conditions and the 'token sales' simulation.
Conditions: 
Fixed token price
Fixed ownership split
Simple registry and repayment (royalties)
Models just one non-fungible asset over multiple sales (max 100)

Functions:
owner creation, each sale is to a unique owner
sales transaction, each sale is for a fixed amount and contains the following
- contains repayment
- splits owner stake in existing token

Things that don't matter at this point:
- the asset itself
- same owner buying the asset multiple times
- price changes
- complex repayment conditions
- infinite sales issues (e.g. one asset changing hands millions of times and breaking eth net)
