### ISSUE TITLE
Bootleg Devkit

### ISSUE THREAD

**Issue by breakpointer** [ConsenSys/web3studio-bootleg#12]
## Overview

As an engineer who wants to use Bootleg-ish like behavior in my app/system/service, I need a development kit with the basic building blocks I need for:

1) Implementing pay-it-backward ERC-XYZ (#4)
2) Doing DRM on chain
3) Supporting the process of art/performance capture in some medium and delivering an encrypted media file and token scheme supporting distributed ownership

...so that I can spend little time understanding how and when to use the provided assets.

### Reference

- Past devkit [Sojourn](https://consensys.github.io/web3studio-sojourn/)

### Questions

- What kind of developer-user are we targeting with this devkit? What content and presentation will appeal the most to them?
- What instrumentation do we need? 
- What schemes can we use to enhance engagement?
- Should we use a mono-repo?

### Assumptions

- We will build the website inside https://github.com/ConsenSys/web3studio-website
- We want to modularize, where it makes sense (tightly coupled repos) we use a monorepo
- Website is JS, any other created repo should choose language and toolset based on the job, need, and problem space

### Acceptance

- Devkit has a website deployed at consensys.net/web3studio/bootleg
- Website references and links to one or more libraries (in any language?)
- Story maps and Journeys (#9) is represented by the devkit
- Devkit has documentation for developers for the libraries
- Analytics
    - We should have a specific set of questions that we are answering and plan to answer them.

## Story Draft

- [x] Validate UX of the devkit
- [ ] What instrumentation do we need on the website?
- [x] Create the content model. 
    - What content do we have that people are interested in?
- [x] Design the PDP for Bootleg 
    - Branding, logo, layout
- [x] Build the site

**Comment by barlock** [comment]
From https://github.com/ConsenSys/web3studio-bootleg/issues/10#issuecomment-454810573

> To tell a solid story and paint a clear picture of how bootleg could work and supply some initial code to inspire and enable folks to make this story a reality.
> 
> Q. What inspires and enables entrepreneurs and developers? How do we reach them? How do we know if it helped anyone get their business started?
> 
> Assumptions: Making a useful, well-thought-out, cleanly coded "devkit" will help the Web3 community see this new vision of the web and persuade them to take action.
> 
> Acceptance: Having something to get feedback if it's helping the community or just "meh" or how we can improve upon it. (obviously not great at writing acceptance criteria)
> 
> Tasks: Content Strategy, Site Architecture, Copy, Wireframe, Interaction Design, UI Design, User Testing

**Comment by breakpointer** [comment]
Done https://consensys.net/web3studio/bootleg/
