### ISSUE TITLE
Dev Team Read devKit and comment

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-bootleg#134]
## Overview

As a developer reader of the devKit, I need to feel respect for the technical description in the devKit, so that I do not decide while reading that the project is stupid or not worth my time and walk away.

### Reference

https://docs.google.com/document/d/1WtjXk0fz8IkksTzKXxSgjH5NxrANNTiQtTTc23dfaYM/edit#

### Questions

- What makes a devKit a "page turner" for developers and technical entrepreneurs.

### Acceptance

- Hadas, Brian and Michael read and comment on the devKit and indicate acceptance of the content (with changes or as-is).

## Tasks

- [x] Michael Read and Comment
- [x] Brian Read and Comment
- [x] Hadas Read and Comment
