### ISSUE TITLE
Make payments owed more clear to token franchisors

### ISSUE THREAD

**Issue by breakpointer** [ConsenSys/web3studio-bootleg#171]
## Overview

As a franchisor I want to know exactly what transactions happened and how they contribute to what by balance is on a token (i.e. a visual payments ledger).

### Assumptions

That it is possible to write a function that returns a list of some sort (or an array/mapping/text string) of the payments for a token franchisor. 
This might not be possible, if it is not then look to implement this in the web3 dApp and expose the payments as enumerable (if they are not already). 

### Acceptance

When a user looks the web UI for the dApp they see all the transactions and how much each one paid them (in eth). 

## Tasks

- [ ] Research what we have implemented currently to aid in supporting this feature.
- [ ] Mock up a way to visualize the payments
- [ ] Implement some enumerable aspect of the token to pull out the payments for the `msg.sender`
