### ISSUE TITLE
Finalize metadata for token and write upload script to IPFS

### ISSUE THREAD

**Issue by breakpointer** [ConsenSys/web3studio-bootleg#173]
## Overview

As a token creator so I can add metadata to my token, create a script to upload the json metadata file to IPFS ahead fo the minting so that the URI in the token is valid and contains the data I expect.

### Reference

- [721 metadata](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md)
- Existing json metadata in the repo
- [OpenSea example](https://docs.opensea.io/docs/2-adding-metadata)
- [Yo Soy](https://github.com/ConsenSys/web3studio-soy)

### Questions

- What exactly are we putting in the metadata file?
- How will we edit it if we need it to change?
- Can we edit it? should we be able to?

### Assumptions

- That we have a URL for the video asset and an image asset for the token

### Acceptance

- upload script as part of the migration file
- re-upload script (separate from migration) to make edits
- json metadata file added to repo (done)
- Text and images and urls all work and are acceptable for launch (i.e. no dummy/test URIs)

## Tasks

- [ ] Look at Soy's upload script and copy it
- [ ] Add upload script to minting
- [ ] Finalize content and copy for the metadata
- [ ] Check to see if the metadata can be displayed in the dApp

**Comment by barlock** [comment]
Here's the actual line from soy that's relevant https://github.com/ConsenSys/web3studio-soy/blob/a4857be9f91f1513c295823b12d72e8cc010fce1/packages/soy-core/src/Soy.js#L95
