### ISSUE TITLE
Implement pay-it-backwards/bootleg to see if it needs it's own ERC

### ISSUE THREAD

**Issue by breakpointer** [ConsenSys/web3studio-bootleg#19]
## Overview

As a web3studio member, so I don't waste everyone's time make sure that pay-it-backward/bootleg embodiment can only be implemented as a new ERC. 

### Reference

- [EIP Workflow](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md#eip-work-flow)

### Questions

- Can we only implement our project if there is a new ERC?

### Assumptions

- none

### Acceptance
- We have attempted to implement pay-it-back/bootleg using existing ERCs and it will not work
- We have raised the idea around of our ERC to the following groups: 1) Ethereum subredit 2) Ethereum gitter chat 3) posted to the issues section of the most similar/viable ERC to pay-it-back/bootleg to get feedback. For 1,2,3 all discussions have lead to a place where implementing an ERC was the only way forward.

## Tasks

- [ ] Review all existing ERC and find one(s) where we could implement a pay-it-back/bootleg concept
- [ ] Attempt to implement concept on existing ERC by creating a POC project on the test nets and trying it out.
- [ ] Show research and POC to ethereum groups (mentioned above) as evidence that a new ERC is needed.

**Comment by breakpointer** [comment]
Maybe try on this https://0xcert.org/use-cases/art-and-gaming ?

**Comment by barlock** [comment]
@breakpointer will rework this either as the top level epic or into smaller stories
