### ISSUE TITLE
SXSW Audition and Approval

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-bootleg#22]
## As Amanda and Jory, I need to see proof that Bootleg and Web3Studio will "kill" at the event, so that we can be confident that the cost and opportunity cost decision are solidly in favor of including them in the event. 

English description of goal in a sentence or two, usually in the form of a user story.

### Reference

- [Reference](links)
- [To issues](or-any-inspiration)
- [That might be](helpful)

### Questions

- List any questions?
- That you are unsure of the answer?

### Assumptions

- List any assumptions that
- You are making in terms of time-frame,
- Output, or general context setting

### Acceptance

- Amanda and Jory announce that at least one of the Web3Studio team will either attend (minimum success) or present (win) at SXSW.

## Tasks

- [x] Create a slide deck (Outline, Copy, Slide Creation, Illustrations and/or Photo gathering, Animation
- [x] Prepare presentation "audition"
- [x] Get time to "audition" with Amanda/Jory/other Catalyst team
- [x] Do the audition
