### ISSUE TITLE
Bootleg DevKit : Content Strategy

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#46]
## Overview

Take outline of DevKit and build layout of devkit (copy, supporting images and/or illustrations etc)

### Reference

- [Reference](links)
- [To issues](or-any-inspiration)
- [That might be](helpful)

### Questions

- What are the priorities of the devKit?
- What is considered success for the devKit
- Is copy sufficient for certain pieces or does it need supporting visual design?

### Assumptions

- 

### Acceptance

- More definition on outline #45 and understanding of what copy needs to be written and what supporting visual design is needed. 
- site architecture
- baseline copy for the devKit
- Hand-sketched layout of devKit 
- Hand-sketched visuals where needed

## Tasks

- [ ] coordinate on how to communicate the main categories in the outline
- [ ] create baseline copy for the devKit
- [ ] create sketches of supporting visual design
- [ ] create sketches of layout

**Comment by humbitious** [comment]
1/2 of copy is ready. Need to carry this forward into the weekend. And I'd say that early next week would be a good time to hammer on visual experience (graphical elements like explainer pictures) and also flow in the UX experience.
