### ISSUE TITLE
Pay-It Backward System

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-bootleg#5]
## Overview

As an entity creating a pay-it-backward system, I need an interoperable standard defining the pay-it-backward token, so that pay it backward interfaces can read and interact with my holdings.

### Reference

- [EIP Github Repo](https://github.com/ethereum/EIPs)
- [Inspiration for the bidding model](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-137.md)
- [a good write-up on the bidding model](https://github.com/ethereum/EIPs/issues/26)
- [Inspiration for non-funginess](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md)
- [A list of everything](https://github.com/jpantunes/awesome-cryptoeconomics)

### Questions

- Is there an existing ERC for the pay it backward model?
    - Can we utilize the ERC 721 (NFT Token)?
- Is this something that fits as an ERC? 
- What is required for an ERC?

### Assumptions

- The ERC should be informed by #7. We should consider the tokens could be used with or without on or off chain DRM schemes. 
- ERC should support implementation of the bootlegging idea, but the namespaces created should be generic for any path following the pay-it-backward model eg: prefer "creator" over "artist"

### Acceptance

- There's a documented "whitepaper" explaining how the PIB system works.
    - Token model application layer, and helix contracts
- Simple bookend model token implementation
- Application layer (eg. The Bootleg App) contract integrating token, helix, and UX work
- Necessary packages are released 
- There is a working example repo to show a happy path automation

## Story Draft

- [x] Understand requirements of making an ERC
- [x] Review existing ERCs and determine if any existing ones can be used (part or in whole).
- [x] Build a proof of concept for PIB
- [x] Implement POC for PIB

**Comment by breakpointer** [comment]
Pretty clear process and guidelines here https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md
 
specifically https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md#eip-work-flow

**Comment by breakpointer** [comment]
This is helpful https://medium.com/decentcrypto/ethereum-ercs-what-are-they-and-which-should-you-know-15289bdb6675

**Comment by breakpointer** [comment]
In terms of the data model around the assets here is a frame work for "community driven IP licensing" https://github.com/COALAIP/specs 
Fast take on it... very simple and somewhat obvious data models for the entities involved in IP. I'm not sure I understand the value of this but it's a start and you gotta start somewhere?
COALAIP was referenced in this article from Ujo https://blog.ujomusic.com/introducing-ujo-portal-making-musicians-more-money-9224d808a57a

**Comment by breakpointer** [comment]
This system is embedded in Bootleg. Considering this completed.
