### ISSUE TITLE
SxSW Presentation : Practice

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#63]
## Overview

Do a few dress rehearsals of the presentation so that we're prepared for SxSW or any other conference

### Reference

- [Reference](links)
- [To issues](or-any-inspiration)
- [That might be](helpful)

### Questions

- List any questions?
- That you are unsure of the answer?

### Assumptions

- List any assumptions that
- You are making in terms of time-frame,
- Output, or general context setting

### Acceptance

- List of what needs to be true
- to consider this done
- done done

## Tasks

- [ ] internal team dress rehearsal
- [ ] ConsenSys Lunch n' Learn
- [ ] Local Meet-Up
