### ISSUE TITLE
UI Design : Buying panel

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#65]
## Overview

What does it look like to purchase a bootleg

### Reference

- [Reference](links)
- [To issues](or-any-inspiration)
- [That might be](helpful)

### Questions

- 

### Assumptions

- Creating the future of smartphone payment options

### Acceptance

- A design of default state of payment, selecting a crypto wallet, displaying crypto wallet as payment, success messaging
- prototyping the connection of all 4 states

## Tasks

- [ ] create default payment
- [ ] create payment selection mode
- [ ] create crypto payment view
- [ ] create success messaging
- [ ] show in user's bootleg library (???)
