### ISSUE TITLE
Task: Write UX Test Questions

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-bootleg#67]
## Overview

Web3Studio needs a structured set of UX research questions and scenarios, so that we can use them to learn the scope and completeness required to tell the bootleg story in a way that motivates entrepreneurs. 

### Acceptance

- List that TJ and John agree on.
- Written-down approach to how to conduct the experiments 
- Delivered as comment in issue

## Tasks

- [x] Brainstorm what we are trying to learn in detail (2hr)
- [x] Write test questions
- [ ] Schedule interviews (to be conducted next sprint)

**Comment by tjchmielewski** [comment]
Testing Protocol for Bootleg	

I want to thank you for taking time out of your day to help me and my team out. We are in the very early stages of a product design concept and are looking to gain some feedback before we move further.

Have you ever done a research interview or tested a digital product before?
So the way this works is I will start with some general questions about your experience with the music industry and afterwards, I will send you a link. When you have the link up, I will ask that you share your screen and we will walk through a lite prototype.

There might be some of my teammates joining the call just to listen. I would also like to record this call if that is ok with you. It will not be shared with anyone outside of our team. It’s just a way for us to check back and make sure we’ve captured all the feedback accurately.

Thank you. Ok. I’m starting the recording now.

So let’s start of with a few general questions...

<industry practitioner questions>
How long have you been in the music industry?
What are some of the biggest differences in the industry when you and started and where it is today?
What would you say are areas that could be improved in the industry today?
Are there processes, if any, that are looking to address them?

I would like to understand how bands get booked. How it all gets paid for. 
Band/Management/Venue/Ticketed relationship.

<questions for all participants>
How many shows have you been to?
Have you been to many in the last year?
Do you have any bands that you are passionate about?
Have you ever been to one of their shows?
Of the shows you’ve been to, are there any that stick out? And Why?
How much would pay to see that show again?
Would you like to see it again from the same seat or it wouldn’t matter?

Great. So we created a prototype called bootleg. In the future, we see the ability for bands to record every show using independent filmmakers. The show footage would be exclusive and fans could purchase the limited releases for their collection and viewing pleasure. The fan could also sell it in the future and the profits would be split between the fan, the band and the filmmaker. 
 
<Walkthrough>
That all said. I want to walk you through a scenario of using bootleg
I’m going to send you a link. And if you could, would you mind sharing your screen?

Before I give you the scenario, I’m going to give you a few ground rules. As you go through the prototype, please talk out loud and let me know what you are thinking. There are no right or wrong answers. We’re not testing you. We’re testing the validity of the prototype and the concept. You won’t hurt our feelings with negative feedback.
