### ISSUE TITLE
Task: Enrich in-code docs 

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-bootleg#70]
## Overview

After architecture is set in and coding is happening, writer needs to monitor repo for docs,  improve language, and extract some of it for devKit content, so that the developers and entrepreneurs that look at our code go, "holy crap, this is the most readable, understandable project I've ever seen...what a joy to work with....hey everyone, have you seen Bootleg?"

### Questions

- When is the right moment for the writer to "get in there"? 

### Assumptions

- The docs are welcome and helpful to the developers using the repo

### Acceptance

- Consistent "keeping up with" the code, so that we don't get to the end of the project and have to rush to get devKit content up.

## Tasks

- [ ] "listener for docs events
- [ ] Reminders to developers to put in the tags
- [ ] Writing writing writing

**Comment by barlock** [comment]
Closing, output is that developers will have a writer review on any block that has documentation in it.
