### ISSUE TITLE
UI : Fan Story Enhancement

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#71]
## Overview

More interesting design concept to attract attention.

### Reference

- [Reference](links)
- [To issues](or-any-inspiration)
- [That might be](helpful)

### Questions

- Is this necessary for what we hope to accomplish?
- ?

### Assumptions

- Adding some "pizzazz" will make the design feel more futuristic and memorable
- Making design dribbble-worthy may attract more designers to our stuff

### Acceptance

- Add Principle animation

## Tasks

- [ ] Sketch out a storyboard for animation
- [ ] Add Figma design to Principle
- [ ] Rename layers to match each other
- [ ] Animate from home screen to band layer
- [ ] Animate band layer to concert
- [ ] Animate concert to bootleg
- [ ] Animate bootleg to payment
- [ ] Animate payment to success/possession of bootleg
- [ ] Save a GIF and movie
