### ISSUE TITLE
bootleg splash screen

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#72]
## Overview

Screen(s) to give context to what the participant is about to experience for testing. 

### Reference

- [https://www.figma.com/file/FUKbSibpuj8eCVDlYjqRHdiX/bootleg?node-id=67%3A0](Figma Link)

### Questions

- Do we need the iphone app homescreen with the app button available
- Should this be a walkthrough screen?
- Do we assume that the participant is a new user and do they need a sign-up screen?

### Assumptions

- We don't need to explain that the user can sample concerts
- We only need to briefly touch on buying selling and residual income
-
### Acceptance

- Needs to have the words "A marketplace to buy and sell exclusive concert videos"

## Tasks

- [x] Create a home screen
- [x] Create a splash screen
- [x] possible walkthrough??
- [ ] slip in the word "artisanal" to make John giggle

**Comment by tjchmielewski** [comment]
![_home](https://user-images.githubusercontent.com/43070257/52371517-c642cf80-2a23-11e9-980f-be533e840f72.png)
![0 0_app_homescreen](https://user-images.githubusercontent.com/43070257/52371518-c642cf80-2a23-11e9-8e88-a7fa51994e97.png)
![walkthrough-2](https://user-images.githubusercontent.com/43070257/52371519-c642cf80-2a23-11e9-861d-a8a4fde22aa3.png)
![walkthrough-3](https://user-images.githubusercontent.com/43070257/52371520-c642cf80-2a23-11e9-978d-ca0f364759c8.png)
![walkthrough-4](https://user-images.githubusercontent.com/43070257/52371521-c642cf80-2a23-11e9-8ebe-4d42873529f2.png)
