### ISSUE TITLE
Selling Bootleg

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#73]
## Overview

Once I've obtained a bootleg, we need to display how we would sell a bootleg. 

### Reference

- [Reference](links)
- [To issues](or-any-inspiration)
- [That might be](helpful)

### Questions

- List any questions?
- That you are unsure of the answer?

### Assumptions

- List any assumptions that
- You are making in terms of time-frame,
- Output, or general context setting

### Acceptance

- List of what needs to be true
- to consider this done
- done done

## Tasks

- [ ] Need to Create Library
- [ ] Create Specific Bootleg page
- [ ] Create flow for how to sell a Specific Bootleg
- [ ] Create flow for how to monitor the sale a Specific Bootleg (optional)
