### ISSUE TITLE
UI Design : Library

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#80]
## Overview

As a user, I want to be able to look into my bootleg collection, so that I can view the video or sell.

### Reference

- [links](https://www.figma.com/file/FUKbSibpuj8eCVDlYjqRHdiX/bootleg?node-id=237%3A528)

### Questions

- What does the user need to see to make an informed decision on how to price their bootleg?
- Is the following flow appropriate...
The chain of custody Bootleg Franchise 33 

 The Band
The Concert (date, location, etc)
The Bootlegger (click to details)
The Bootleg (video format, duration, etc...stuff that would be common to all Issuances of this bootleg regardless of the "Print #"
The Print: You are holding 33, You are the 3rd owner in the Franchise. 

 No.33 of 100
On the "Market" screen, average purchase price to date of all Prints. Total revenue on this Print (how much has the three turns of this made)

Average price of this Print to date

Also on Market Screen:
1) Requests to purchase (number with click through to see details)
2) Last time any of the Prints had sold(?)
3) Suggest sale price based on average latest purchases and current level of interest (from requests) 

### Assumptions

- Owner can price their bootleg print from their library
- 

### Acceptance

- Ability to see list of bootlegs in a user's collection
- understanding of what print they have
- understanding of what generation they are in the purchasing order
- ability to play bootleg
- ability to sell bootleg
- some guidance on how to price/sell

## Tasks

- [x] Create Library Screen
- [x] Create some connection between sale of bootleg and it populating in the user's library (confirmation)
- [x] Create Bootleg Print view
- [x] Create sale of a bootleg Print

**Comment by tjchmielewski** [comment]
![2 0_library-w2](https://user-images.githubusercontent.com/43070257/52487592-f907d780-2b8b-11e9-8c70-da038ea0eb74.png)
![2 0_library-w3](https://user-images.githubusercontent.com/43070257/52487593-f907d780-2b8b-11e9-8e76-55538e6a4291.png)
![2 1_print](https://user-images.githubusercontent.com/43070257/52487594-f907d780-2b8b-11e9-9e6f-c2506394860b.png)
![2 1 2_print](https://user-images.githubusercontent.com/43070257/52487595-f9a06e00-2b8b-11e9-820c-db66ff6513dc.png)
![2 1 3_print](https://user-images.githubusercontent.com/43070257/52487596-f9a06e00-2b8b-11e9-9f91-22a8e7676b91.png)
