### ISSUE TITLE
Bootleg Transfer dApplication

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-bootleg#88]
## Overview

As a person who is going to participate with our Bootleg demo sale process. 

## Expected Value
This simple dApp will help make the buying/transfer process for our pre-pre-alpha test users. It will also help solidify the Bootleg use case for people discovering/using the repo.

### Questions

- Can we make it work with one-click-dapp.com?
- Do we need to do enumerable methods?

### Assumptions

- There will be a simple one-button/form interface
- It will use meta-mask

### Acceptance

- There is a simple application or set of command line tools that:
    - Allows for purchase a PIB Token
    - Force that the bootleg app contract is always "approved" mostly for demo purposes

## Story Draft

- [ ] Build Bootleg App Contract 
    - Deployed  testnets
- [ ] Build Bootleg Token Contract
    - Deployed testnets
- [ ] Simple web app, really should only contain a "Buy" button and a form for wallet address.
